package crypto

import "testing"

const certExample =`
-----BEGIN CERTIFICATE-----
MIICQzCCAeqgAwIBAgIRAJ1WKngOM7+D48dY1wiKKGIwCgYIKoZIzj0EAwIwczEL
MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
Lm9yZzEuZXhhbXBsZS5jb20wHhcNMTcwOTI5MDExNjI5WhcNMjcwOTI3MDExNjI5
WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
BJ4q+NT0F6yhU7tRc4WDs/Dd+iVuzLR2zQIwAHUJFpHs1dyHjS1awPgWMZQ+0cZN
9/g+ljoR8BqFECasV+ik7LKjXzBdMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAG
BgRVHSUAMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIDtCURrbj5cx98lTqVOS
hPtTlaf1Vl+D+bCGdgPuzM9QMAoGCCqGSM49BAMCA0cAMEQCIGn4eOM6TgqCbimX
2FN/dFc2VIZ2rDxye8wS/R/RuXsUAiAgPWiKqiIim+E8zX5c8innadmNegjWouHs
WcNNpsFRyA==
-----END CERTIFICATE-----`

func TestDecodeCertificate(t *testing.T){
	err := DecodePemCertificate(certExample)
	if err != nil{
		t.Error(err)
		t.Fail()
	}
}
